### ISSUE TITLE
How to use a Persistent Store (database) for the config

### ISSUE THREAD

**Issue by regul4rj0hn** [rizamarhaban/IdentityServer4Demo#1]
I am trying to upgrade both IS4 and .Net Core to 2.0.0. I was using an Identity Server database for the configuration store before. I have obviously created the database using entity framework and the IdentityServer4 migration, this is all on production.
I've cloned your project to give it a go and started configuring things, everything seems fine when using InMemory objects, but how would I go around using the DB on version 2?

Eg. Before, I was doing this, but it seems like the UseSqlServer methods are no longer available:

```
services.AddIdentityServer()
    .AddDeveloperSigningCredential()
    .AddTestUsers(Users.GetUsers())
    .AddConfigurationStore (builder =>
        builder.UseSqlServer (connectionString, options =>
            options.MigrationsAssembly (migrationsAssembly)))
    .AddOperationalStore (builder =>
        builder.UseSqlServer (connectionString, options =>
            options.MigrationsAssembly (migrationsAssembly)));
```

Any help is appreciated.
Thanks in advance!

**Comment by rizamarhaban** [comment]
You can use and implement the ```IdentityServer4.EntityFramework``` for the configuration. Check this one: https://github.com/IdentityServer/IdentityServer4.EntityFramework
