### ISSUE TITLE
Few issues with initial launch

### ISSUE THREAD

**Issue by rlee923** [rizamarhaban/IdentityServer4Demo#2]
Hi,

I actually wanted to ask some questions but I couldn't find a good communication channel so I decided to post it here.

Firstly the IdentityServer is configured to use port 6000 for IIS express, wondering why it's configured this way? Because when I try to run the app in Visual Studio, it causes issues with launching the browser. So with this I had to configure it to 12936 in the launchsettings.json file, and the startup.cs in MyWeb Application.
After this when I run these two applications, MyWeb application browser launch automatically redirect to IdentityServer and comes up with an error message saying that:

Swapping to Development environment will display more detailed information about the error that occurred

When both of them are already running under development environment.

Could you please let me know what I am doing wrong here?

Thanks.

**Comment by rizamarhaban** [comment]
You just go to the project web configuration, choose don't open browser option for the IdentityServer and MyApi project. Also, I prefer to use web project instead of IISExpress.

**Comment by AbuHelweh** [comment]
Same here, I can't  access port 600 UNSAFE_PORT

I then started the console without Luch URL using IdentityServer run option 
Then I tried the MyWeb App using http://localhost:14336/ then I got an error 
![error1](https://user-images.githubusercontent.com/5153946/30558691-5ed32014-9cc3-11e7-8175-1da8c0733682.png)
![error3](https://user-images.githubusercontent.com/5153946/30558690-5ed15022-9cc3-11e7-9c8d-e8ea8a459e5a.png)


 attached  screenshots

**Comment by LindaLawton** [comment]
This is a setting in chrome.    [How to fix ERR_UNSAFE_PORT error on Chrome when browsing to unsafe ports](https://superuser.com/q/188006/414992)

--explicitly-allowed-ports=5000,6000,7000

**Comment by iamzaker** [comment]
@rlee923  and @AbuHelweh  did u guys were able to fix this ?
